In [4]:
import pandas as pd
import numpy as np

## Q1. Pandas version
What's the version of Pandas that you installed?

You can get the version information using the __version__ field:

In [96]:
pd.__version__

'2.3.2'

## Q2. Records count
How many records are in the dataset?

In [2]:
# !wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2025-09-25 18:26:34--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv’

car_fuel_efficiency 100%[===================>] 853.70K  4.03MB/s    in 0.2s    

2025-09-25 18:26:34 (4.03 MB/s) - ‘car_fuel_efficiency.csv’ saved [874188/874188]



In [5]:
df = pd.read_csv("car_fuel_efficiency.csv")
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [6]:
len(df)


9704

## Q3. Fuel types
How many fuel types are presented in the dataset?

In [9]:
df["fuel_type"].unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [10]:
len(df["fuel_type"].unique())

2

## Q4. Missing values
How many columns in the dataset have missing values?
(https://youtu.be/0j3XK5PsnxA?t=1505)

In [13]:
nan_counts = df.isna().sum()
nan_counts[nan_counts > 0]

num_cylinders    482
horsepower       708
acceleration     930
num_doors        502
dtype: int64

## Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?

In [17]:
filtered_cars = df[df["origin"] == "Asia"]
# df[dell_laptops]["Final Price"].max()
filtered_cars["fuel_efficiency_mpg"].max()

np.float64(23.759122836520497)

## Q6. Median value of horsepower
- Find the median value of horsepower column in the dataset.
- Next, calculate the most frequent value of the same horsepower column.
- Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
- Now, calculate the median value of horsepower once again.


Has it changed?

- Yes, it increased
- Yes, it decreased
- No


### The median value of the 'horsepower' column in the dataset.

In [19]:
df["horsepower"].median()

np.float64(149.0)

#### The most frequent value of the same 'horsepower' column

In [20]:
df["horsepower"].mode().iloc[0]

np.float64(152.0)

#### Use fillna method to fill the missing values in 'horsepower' column with the most frequent value from the previous step.

In [21]:
df["horsepower"].fillna(df["horsepower"].mode().iloc[0])

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

#### Calculate the median value of the 'horsepower' column once again

In [23]:
df["horsepower"].median()

np.float64(149.0)

### Q7. Sum of weights

1. Select all the cars from Asia
2. Select only columns `vehicle_weight` and `model_year`
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Invert `XTX`.
7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the sum of all the elements of the result?

> **Note**: You just implemented linear regression. We'll talk about it in the next lesson.

In [35]:
filtered = df[df["origin"] == "Asia"][["vehicle_weight", "model_year"]]
X = filtered.head(7).to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [36]:
X.T

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [37]:
XTX = np.dot(X.T, X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [38]:
XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [39]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [40]:
# Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
w = np.dot(np.dot(XTX_inverse, X.T), y)
w

array([0.01386421, 0.5049067 ])

In [41]:
sum = w.sum()
sum

np.float64(0.5187709081074016)