In [95]:
import pandas as pd
import numpy as np

## Q1. Pandas version
What's the version of Pandas that you installed?

You can get the version information using the __version__ field:

In [96]:
pd.__version__

'2.3.2'

## Q2. Records count
How many records are in the dataset?

In [97]:
df = pd.read_csv("laptops.csv")
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [98]:
len(df)


2160

## Q3. Laptop brands
How many laptop brands are presented in the dataset?

In [99]:
len(df["Brand"].unique())

27

## Q4. Missing values
How many columns in the dataset have missing values?
(https://youtu.be/0j3XK5PsnxA?t=1505)

In [100]:
nan_counts = df.isna().sum()
nan_counts[nan_counts > 0]

Storage type      42
GPU             1371
Screen             4
dtype: int64

## Q5. Maximum final price
What's the maximum final price of Dell notebooks in the dataset?

In [101]:
dell_laptops = df[df["Brand"] == "Dell"]
# df[dell_laptops]["Final Price"].max()
dell_laptops["Final Price"].max()

np.float64(3936.0)

## Q6. Median value of Screen
- Find the median value of Screen column in the dataset.
- Next, calculate the most frequent value of the same Screen column.
- Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
- Now, calculate the median value of Screen once again.
- Has it changed?

- Hint: refer to existing mode and median functions to complete the task.
  - Yes
  - No


### The median value of Screen column in the dataset.

In [102]:
df["Screen"].median()

np.float64(15.6)

#### The most frequent value of the same Screen column

In [103]:
df["Screen"].mode().iloc[0]

np.float64(15.6)

#### Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.

In [104]:
df["Screen"].fillna(df["Screen"].mode().iloc[0])

0       15.6
1       15.6
2       15.6
3       15.6
4       15.6
        ... 
2155    17.3
2156    17.3
2157    17.3
2158    13.4
2159    13.4
Name: Screen, Length: 2160, dtype: float64

#### Calculate the median value of Screen once again

In [105]:
df["Screen"].median()

np.float64(15.6)

### Q7. Sum of weights

1. Select all the "Innjoo" laptops from the dataset.
2. Select only columns `RAM`, `Storage`, `Screen`.
3. Get the underlying NumPy array. Let's call it `X`.
4. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
5. Compute the inverse of `XTX`.
6. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100]`.
7. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
8. What's the sum of all the elements of the result?

> **Note**: You just implemented linear regression. We'll talk about it in the next lesson.

In [106]:
X = df[df["Brand"] == "Innjoo"][["RAM", "Storage", "Screen"]].to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [107]:
X.T

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [108]:
XTX = np.dot(X.T, X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [109]:
XTX_inverse = np.linalg.inv(XTX)
XTX_inverse

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [110]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [111]:
# Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
w = np.dot(np.dot(XTX_inverse, X.T), y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [112]:
sum = w.sum()
sum

np.float64(91.2998806299555)